[[jemalloc]]
arch = "aarch64"
git-tree-sha1 = "c0b021ea859e7e107e24a6bc22e749cee1179cc8"
os = "macos"

    [[jemalloc.download]]
    sha256 = "dde4ee4e7254d32c7e7e7a3b024c0fd4fdceb6c3292da684012ad573cf274851"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.aarch64-apple-darwin.tar.gz"
[[jemalloc]]
arch = "aarch64"
git-tree-sha1 = "d1d6343d6e32f42f4a83e7c0ff8c5ab267069a47"
libc = "glibc"
os = "linux"

    [[jemalloc.download]]
    sha256 = "2b8c944b991321a6614c6404d0a31300ea372fbe81693035d4ee71cb567ecdf9"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.aarch64-linux-gnu.tar.gz"
[[jemalloc]]
arch = "aarch64"
git-tree-sha1 = "c540dfd011caf7413f260817a5d56455704cf22e"
libc = "musl"
os = "linux"

    [[jemalloc.download]]
    sha256 = "d46cd42889900405e6dcb2d51ebe61f466293286c804ecfa847bc687feb3d31f"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.aarch64-linux-musl.tar.gz"
[[jemalloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "41bf5f9a5c0710e088cf453d40a238f2040150e4"
libc = "glibc"
os = "linux"

    [[jemalloc.download]]
    sha256 = "647d130089c0223c993d4b5f5040c59daa2929a7dc97a39587a4b4aacac3f411"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.armv6l-linux-gnueabihf.tar.gz"
[[jemalloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "790b25eb322d36fb3cee877f971ef2e3ea136f5e"
libc = "musl"
os = "linux"

    [[jemalloc.download]]
    sha256 = "45ebd98befe54e796e169f8d2b35946fe9d91dbcee3d66c8a98bf22f560ef1a1"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.armv6l-linux-musleabihf.tar.gz"
[[jemalloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "539d8f654ced1ed0c92b117b9279868d6f926cac"
libc = "glibc"
os = "linux"

    [[jemalloc.download]]
    sha256 = "7e61da5595a9e7c980454e982fa2f8b1f8334112d6d9ca6bde33303ccbaff98b"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.armv7l-linux-gnueabihf.tar.gz"
[[jemalloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94348ae6dc9101b521e50de63f74df1a256230ce"
libc = "musl"
os = "linux"

    [[jemalloc.download]]
    sha256 = "64deeb46da17c14fd90ebe421d11b5feb9b93e84ca5e24e209e85cfdd491c26e"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.armv7l-linux-musleabihf.tar.gz"
[[jemalloc]]
arch = "i686"
git-tree-sha1 = "8cecbc64243d1e5057f49dfd5111afb9fdcbdf02"
libc = "glibc"
os = "linux"

    [[jemalloc.download]]
    sha256 = "17ce034a7204e6a1d07b0375de4b09042b2fbb9bcd875f90c9ca5b9d6e286be4"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.i686-linux-gnu.tar.gz"
[[jemalloc]]
arch = "i686"
git-tree-sha1 = "8618f46e6c64cf25dd5e3b9ef839d32a258c0c2a"
libc = "musl"
os = "linux"

    [[jemalloc.download]]
    sha256 = "cac1a424f2be06f58447daa8cdfb2326c3ac66209f878dab371f3b3e63d5c4fe"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.i686-linux-musl.tar.gz"
[[jemalloc]]
arch = "i686"
git-tree-sha1 = "2182c0b21ef649bedb84fcfdf9e4a86a76bcdc40"
os = "windows"

    [[jemalloc.download]]
    sha256 = "9f8b3c67b60bb4b0e89559a36db31e05982c34037e86d5b725780ab44722f09b"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.i686-w64-mingw32.tar.gz"
[[jemalloc]]
arch = "powerpc64le"
git-tree-sha1 = "4c970d690121575eb448da5395a1ee90c69c57ca"
libc = "glibc"
os = "linux"

    [[jemalloc.download]]
    sha256 = "9f6e83cad315b42b9ea7ca11525e111adc84f5348e8be1d7337803c2fba4c351"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.powerpc64le-linux-gnu.tar.gz"
[[jemalloc]]
arch = "x86_64"
git-tree-sha1 = "a4c26f446d29f5a858b0770faae7f29fec4b13fd"
os = "macos"

    [[jemalloc.download]]
    sha256 = "0e9c6c483db03341a29564bee077d84aa0be695ba4b3953346040623112490f2"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.x86_64-apple-darwin.tar.gz"
[[jemalloc]]
arch = "x86_64"
git-tree-sha1 = "d0e2e51d657cedba804e5a372f6342baade9b143"
libc = "glibc"
os = "linux"

    [[jemalloc.download]]
    sha256 = "1788b08007c7072f04641eda912f11618b34ffcf495635b2afea6732d98d99bd"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.x86_64-linux-gnu.tar.gz"
[[jemalloc]]
arch = "x86_64"
git-tree-sha1 = "0ad5b8e3acfc1f65df28db4b3c7ae7d1f4d7992c"
libc = "musl"
os = "linux"

    [[jemalloc.download]]
    sha256 = "ab3f5011326652e0289d00d99b2500976b5bfb3def81979e600693163f4be1ff"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.x86_64-linux-musl.tar.gz"
[[jemalloc]]
arch = "x86_64"
git-tree-sha1 = "f5c4ef4ab43ae013494be6a9460d46aeca600ac3"
os = "freebsd"

    [[jemalloc.download]]
    sha256 = "d6763fec15a3459f1149366dfef6abae75041de85a632993751230841229032e"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.x86_64-unknown-freebsd.tar.gz"
[[jemalloc]]
arch = "x86_64"
git-tree-sha1 = "8e2f2cd7ccd2d011819402f98365ad33a310499b"
os = "windows"

    [[jemalloc.download]]
    sha256 = "df3fc7923db109f250bb88d8e48bbf2f33486f7def2aa24f56d2bd9f4d5df22f"
    url = "https://github.com/JuliaBinaryWrappers/jemalloc_jll.jl/releases/download/jemalloc-v5.3.0+0/jemalloc.v5.3.0.x86_64-w64-mingw32.tar.gz"
